{{- if not .Values.auth.secretName -}}
{{- if ne .Values.auth.actions "." -}}
apiVersion: v1
kind: Secret
type: Opaque
stringData:
  auth: |-
  {{- range $key, $value := .Values.auth.credentials }}
    {{ $key }}:{{ $value }}
  {{- end }}
metadata:
  name: {{ include "pypiServer.fullname" . }}
  labels:
    {{- include "pypiServer.labels" . | nindent 4 }}
{{- end -}}
{{- end -}}