apiVersion: v1
kind: Service
metadata:
  name: {{ include "pypiServer.fullname" . }}
  labels: 
    {{- include "pypiServer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector: {{- include "pypiServer.selectorLabels" . | nindent 4 }}
